version = 0.1

[default.deploy.parameters]
stack_name = "try-bref-sam"
resolve_s3 = false
s3_bucket = "try-bref-sam"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "ap-northeast-1"
